version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "5002:5002"
    networks:
      - app-network
    restart: unless-stopped

  ping:
    image: alpine:3.20
    command: ["sh", "-c", "sleep 2 && wget -qO- http://api:5002/"]
    networks:
      - app-network
    depends_on:
      - api

networks:
  app-network:
    driver: bridge